#!/bin/bash
#this script replaces the normal shutdown function, so that when the iStraStream script calls it when add a file to the shutdown calls directory
username=$(pwd | pwd | cut -d '/' -f3 )
logger -s -t $username Shutdown call made
mv /home/gmn/states/camerasrunning/$username /home/gmn/states/camerasstopped/

